### ISSUE TITLE
Upgrade to Elm 0.17

### ISSUE THREAD

**Issue by bendiksolheim** [wernerdegroot/ListZipper#1]
Hello!

I have a specific problem I believe zipper lists will solve, and your library seems like a really nice implementation. Easy to use, and (especially appreciated) the code is small and easy to read. Sadly, it has not been updated to Elm 0.17 yet. I don't think it is too much of a job as you don't seem to use any of the features changed/removed, but I don't have the knowledge to say for sure. Would you consider updating it and push a new version to elm-packages? Or would you rather take a pull request? I could provide one in the coming week if you don't fancy doing it yourself :)

**Comment by wernerdegroot** [comment]
Hi!

Thank you for your kind words! Nice to know someone is interested in using
my library. I'll gladly take a pull request, because I haven't transitioned
to 0.17 myself (and I'm not really sure what the changes are exactly... I
believe trampolines are no longer necessary?)

With kind regards,

Werner

Op zaterdag 24 september 2016 heeft Bendik Solheim notifications@github.com
het volgende geschreven:

**Comment by bendiksolheim** [comment]
I’ll be honest: I only started programming in Elm when 0.17 was released, so I don’t have any experience with 0.16 at all. 

However, there are official guides to migrating from 0.16 to 0.17 [0], and it seems pretty straight forward. Especially since your code doesn’t use the old signal stuff at all. And regarding the trampoline, it seems that trampolines are only necessary with mutually recursive functions [1], so I’m pretty sure it can be safely removed.

I’ll start on a pull request :)

[0] - https://github.com/elm-lang/elm-platform/blob/master/upgrade-docs/0.17.md
[1] - http://package.elm-lang.org/packages/elm-lang/trampoline/1.0.0/

**Comment by bendiksolheim** [comment]
A pull request in #2 has been created.

**Comment by wernerdegroot** [comment]
Thanks Bendik! A new version, compatible with Elm 0.17 is now available!
