### ISSUE TITLE
Update to Elm 0.18

### ISSUE THREAD

**Issue by jschomay** [wernerdegroot/ListZipper#11]
Great library, I use it often in production code :)

And... that production code wants to be Elm 0.18 now, and as I depend on this package, I need it updated too.

Do you have this in action already?  If not, I may make a fork and PR, but I wanted to check first if you had it underway.

Thanks!

**Comment by stoeffel** [comment]
Awesome! Do you know about https://github.com/avh4/elm-upgrade?

**Comment by wernerdegroot** [comment]
I'm not currently working on this. I have time somewhere this week. If you wish to speed it up, I'll happily accept a PR!

The following part of the examples can now be removed in favor of the new `andThen`:

```elm
-- Just for convenience:
flatMap = flip andThen
```

**Comment by wernerdegroot** [comment]
Done! 👍
