### ISSUE TITLE
`find` doesn't look in the `before` list

### ISSUE THREAD

**Issue by Keyamoon** [wernerdegroot/ListZipper#13]
`find` is only looking in the `after` list.
As a workaround, I used `first` and then passed its result to `find`.

**Comment by wernerdegroot** [comment]
That is, in fact, by design. This way you can start from the last occurrence and find the next one. 

```elm
firstEven = find even myZipper
secondEven = firstEven
  |> Maybe.andThen next
  |> Maybe.andThen (find even)
```

Any suggestions how to make that more clear?

**Comment by stoeffel** [comment]
I used the same workaround as @Keyamoon as well and saw that devs without previous exposure to `listzipper` stumble over this.

💭 Maybe it should be renamed to `findNext`...

**Comment by wernerdegroot** [comment]
So, in terms of the current `find`:

```elm
findFirst predicate = first >> find predicate
findNext predicate zipper = zipper
  |> next
  |> Maybe.andThen (find predicate)
```

Is that better?

**Comment by Keyamoon** [comment]
`findFirst` would help. Updating the docs alone might suffice. I checked it but it didn't say anything about `find` not  searching the entire list.

**Comment by wernerdegroot** [comment]
Thanks you for your contribution! I'll publish a new version after we've resolved everything in issue https://github.com/wernerdegroot/listzipper/issues/15
