### ISSUE TITLE
Implementation of withDefault

### ISSUE THREAD

**Issue by ptkato** [wernerdegroot/ListZipper#16]
I'm confused, shouldn't it be `Zipper a -> Maybe (Zipper a) -> Zipper a` instead of `a -> Maybe (Zipper a) -> Zipper a`?

I don't see why I would want to get an `a` if I originally wanted a `Zipper a`.

**Comment by wernerdegroot** [comment]
The `withDefault` you are describing is the default `Maybe.withDefault`. If that is what you need, I suggest you use that. 

For some users, the `withDefault` for `Zipper` has proven to be useful. When constructing a `Zipper` from an empty list fails (as it always will), you might provide an element of type `a`, to construct a `Zipper` from. This `Zipper` will only contain that single element. It is simply a convenience function:

```elm
withDefault = Maybe.withDefault << singleton
```

**Comment by wernerdegroot** [comment]
Hi @ptkato, does that answer your question?

**Comment by ptkato** [comment]
Yeah, it does.
