### ISSUE TITLE
Tests fail?

### ISSUE THREAD

**Issue by squaresurf** [wernerdegroot/ListZipper#17]
I cloned this repo and checked out "3.0.0", but I can't seem to run the tests. I currently have elm-test version "0.18.8" installed alongside elm version "0.18.0". I run into the following error when I run `elm-test` in the main directory. How am I supposed to run the tests for this repo? I wouldn't be so concerned about running the tests if they already ran on travisci or the like.

```
2017-09-06 08:34:29 [±bfb60c9] ~/code/elm/listzipper 
$ elm-test
Success! Compiled 50 modules.                                       
Successfully generated /dev/null
I found multiple modules named 'Test.Runner.Node'.

Module 'Test.Generated.Main2136539251' is trying to import it.

Modules with that name were found in the following locations:

    directory /Users/daniel/.asdf/installs/nodejs/7.8.0/.npm/lib/node_modules/elm-test/src/Test/Runner/Node.elm
    package rtfeldman/node-test-runner

Compilation failed for /Users/daniel/code/elm/listzipper/elm-stuff/generated-code/elm-community/elm-test/src/Test/Generated/Main2136539251.elm
```

**Comment by wernerdegroot** [comment]
Thanks for reporting! I'll look into this this week.

**Comment by wernerdegroot** [comment]
The repository is currently being built by Travis on every commit. Tests are running and passing. Closing the issue.

**Comment by squaresurf** [comment]
Thank you! I'll take a look at the travis.yml to see an example.

**Comment by wernerdegroot** [comment]
You should be able to run `elm-tests` now. There was something wrong with the test files, that was why you couldn't run any tests before. That should be fixed now 👍

**Comment by squaresurf** [comment]
Awesome! Thank you so much!

**Comment by squaresurf** [comment]
All tests pass for me! I also really appreciate you setting up travis and putting on the README.md. That is what I looked for at first when I saw all your tests.
