### ISSUE TITLE
Support elm 0.19

### ISSUE THREAD

**Issue by eelcoh** [wernerdegroot/ListZipper#23]
Would it be possible to upgrade this package to elm 0.19?

**Comment by wernerdegroot** [comment]
I haven't been using Elm for a while now, so I'm not certain about the effort that would take. Is it only updating the elm-package.json, or are there other changes involved? If so, would you mind creating a PR?

**Comment by eelcoh** [comment]
The code itself is easily ported with elm-upgrade. The test suite depends on elm-community's lazy list, which has not been ported yet.

**Comment by eelcoh** [comment]
created pull request #24

**Comment by wernerdegroot** [comment]
Published 3.1.1.
