### ISSUE TITLE
can't install this package

### ISSUE THREAD

**Issue by stoeffel** [wernerdegroot/ListZipper#3]
Hey! This module looks nice!

I was just trying to install it, but it failed to download (see error message below). I tried it on different machines and also on a co-workers machine. I think the problem is that this repo is named differently than the repo in `elm-package.json`. So I think the solution would be to rename this repo to match `elm-package.json`.

Thanks 😻 

```
❯ elm-package install wernerdegroot/listzipper
Some new packages are needed. Here is the upgrade plan.

  Install:
    wernerdegroot/listzipper 1.0.2

Do you approve of this plan? [Y/n] y
Starting downloads...

  ✗ wernerdegroot/listzipper 1.0.2
Error: Problem when downloading the wernerdegroot/listzipper 1.0.2 code.
```

**Comment by wernerdegroot** [comment]
I've renamed the repo (all lowercase characters now). Does that fix your problem?

**Comment by stoeffel** [comment]
Yes, it works now!
Thanks for the fast response.

**Comment by wernerdegroot** [comment]
I think that it must be an 0.17 thing, as this never appeared to be a problem with me in Elm 0.16
