### ISSUE TITLE
changing fromList to not return Maybe (Zipper a)

### ISSUE THREAD

**Issue by stoeffel** [wernerdegroot/ListZipper#4]
How do you feel about changing `fromList` to be like:

`fromList : a -> List a -> Zipper a`
The first arg is the currently focused element and the list is `previous`.
It would be just more convenient to not have a `Maybe`.
I know you could just do `Zipper [] 1 [2,3,4,5]`, but this just doesn't feel nice.
One other option would be to have it as a separate function, instead of changing `fromList`.

Will open a PR if you like the idea.

**Comment by wernerdegroot** [comment]
I have struggled with this quite a bit myself, to be honest (where should the `Maybe` go?)

I think both use cases are valid (both constructing a `Zipper` with a head and a tail, as you propose and constructing one from a `List` that might be empty). I would therefore prefer a separate function.

**Comment by stoeffel** [comment]
> I would therefore prefer a separate function.

SGTM. How about naming it `fromListWithFocussed`.

...or maybe another solution would be

``` elm
withDefault : a -> Maybe (Zipper a) -> Zipper a
withDefault default maybeZipper =
  Maybe.withDefault (Zipper [] default []) maybeZipper
```

``` elm
[1,2,3,4,5]
  |> List.Zipper.fromList
  |> List.Zipper.withDefault 1

-- Zipper [] 1 [2,3,4,5]

[]
  |> List.Zipper.fromList
  |> List.Zipper.withDefault 1

-- Zipper [] 1 []
```

maybe it should be named `withFocussed` though.

**Comment by stoeffel** [comment]
After thinking about it, I think that I like `withDefault` / `withDefaultFocussed` better than having a separate function like `fromListWithFocussed`.
What do you think?

off topic: I will probably also open a PR to update elm test to the newest version and add fuzz tests. If you are open to that.

**Comment by wernerdegroot** [comment]
I like your proposal! 

The last question I have is whether we'd end up with more _orthogonal_  functions if we would provide a `singleton x = Zipper [] x []` which we can then combine with `Maybe.withDefault` to get the `List.Zipper.withDefault` you are proposing? Something like

``` elm
[1,2,3,4,5]
  |> List.Zipper.fromList
  |> Maybe.withDefault (List.Zipper.singleton 1)
```

The downside, of course, would be an extra function to call, so I have little preference for one over the other.

About the update of elm-test, I would love to see some fuzz tests! Is that something similar to property based testing?

**Comment by stoeffel** [comment]
💭 I'm ambivalent about that. I think both `singleton` and `withDefault` are nice.

> About the update of elm-test, I would love to see some fuzz tests! Is that something similar to property based testing?

yes. I think I will have some time this weekend.

**Comment by wernerdegroot** [comment]
Let's do both! I'll try to add both functions tomorrow and make a release.

**Comment by stoeffel** [comment]
let me know if I can help.

**Comment by wernerdegroot** [comment]
Just added the two new functions (commit 0d0c7ae24aca0ee93e94a2034b349259d3c5ef4b). If you agree, I'll make a release.

**Comment by stoeffel** [comment]
looks great! go for it :+1:
