### ISSUE TITLE
renaming get

### ISSUE THREAD

**Issue by stoeffel** [wernerdegroot/ListZipper#5]
This is really opinionated.

I think `get` isn't really expressive.
IMHO `current` or `focussed` would communicate better.

Feel free to just close this again if you're happy with the current name.

**Comment by wernerdegroot** [comment]
Renamed `get` (commit a53dfd843e18b0c12af55d339f05bc0a636a4f20). If you agree, I'll make a release.

**Comment by stoeffel** [comment]
:tada:
