### ISSUE TITLE
crazy idea

### ISSUE THREAD

**Issue by stoeffel** [wernerdegroot/ListZipper#8]
This might be a crazy idea and I don't know think I like it, but I thought I will share it with you @wernerdegroot.

Zipper now has a `ZipperStart` and `ZipperEnd`.

``` elm
{-| The `Zipper` type. -}
type Zipper a 
    = ZipperStart a (List a)
    | Zipper (List a) a (List a)
    | ZipperEnd (List a) a
```

This way we can change functions like `next` from returning `Maybe (Zipper a)` into `Zipper a`.

``` elm
next : Zipper a -> Zipper a
next zipper =
  case zipper of
    ZipperStart x rs -> 
      case rs of
        [] -> zipper
        [y] -> ZipperEnd [x] y
        y :: ys -> Zipper (x :: rs) y ys
    Zipper ls x rs -> 
      case rs of
        [] -> zipper
        [y] -> ZipperEnd (x :: ls) y
        y :: ys -> Zipper (x :: ls) y ys
    ZipperEnd _ _ -> zipper
```

This way we can also nicely initialize zippers like:

``` elm
foo = ZipperStart 1 [2, 3, 4, 5]
bar = Zipper [-1, -2] 0 [1, 2, 3, 4]
foo = ZipperEnd [2, 3, 4, 5] 6
```

The nice thing about this is, that you can just call `next` as many times as you want and just update your `Zipper` without having to handle `Maybe`, because it will just stay at the end.

``` elm
update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
  case msg of
    Next -> 
    { model | List.Zipper.next model }

view : Model -> Html Msg
view model =
  case model of
    ZipperStart current _ -> viewStart current
    Zipper _ current _ -> viewInProgress current
    ZipperEnd _ current -> viewEnd current
```

But I think it's better to keep it as is, because it's much simpler and probably has more use-cases than this.

**Comment by wernerdegroot** [comment]
I think I was initially struggling with the `Maybe` as much as you appear to be now. I think I even toyed with the same idea as you are proposing. After giving it a lot of thought I came to the conclusion that either
- We need something to alleviate the syntactic pain of `Maybe`, for instance with [do-notation](https://en.wikibooks.org/wiki/Haskell/do_notation), as this seems to be the main issue.
- The type system _should_ be able to know whether a `Zipper` has any remaining elements or not, so I could keep on applying `next` until I'm at the end of the list. This would require [dependent types](https://en.wikipedia.org/wiki/Dependent_type) however. 

I was also thinking of providing a function to construct a `Zipper` from a [non-empty list](http://package.elm-lang.org/packages/mgold/elm-nonempty-list/2.0.0/List-Nonempty), but I didn't really go through with it.

Of course, we could provide the functionality you'd like with functions such as `nextIfPossible` and `previousIfPossible` using the current `Zipper`-type. Would that solve your use case?

**Comment by stoeffel** [comment]
I actually don't have a use-case for it, I think it's totally fine as is. I was just thinking about it and thought I would share it with you. I think, we shouldn't change anything.

**Comment by stoeffel** [comment]
I think we should keep the APi as small as possible and avoid adding to many functions. I think it's easy enough to add stuff like `nextIfPossible` on your own if needed. also I think it's not worth integrating with non-empty list since we have `withDefault` now.

**Comment by stoeffel** [comment]
thanks for your thoughts on it though ❤️
