### ISSUE TITLE
mapping zipper

### ISSUE THREAD

**Issue by stoeffel** [wernerdegroot/ListZipper#9]
A few thoughts about updating/mapping zipper. 

A `List.Zipper.map` function would be nice.
`map : (a -> b) -> Zipper a -> Zipper b`.

e.g. `List.Zipper.map toString myZipper`

I also think that `update(Before/After)` would be better named `map(Before/Current/After)`.
and maybe the api of `map(Before/After)` more like the api of `map(Current)`.

`mapBefore : (a -> a) -> Zipper a -> Zipper a`

What do you think?

**Comment by wernerdegroot** [comment]
I agree that `map` would be a nice addition!

Given `map`, I also tend to agree that `map(Before/After)` is a better name than `update(Before/After)`. Would you also say that `update` should be renamed to `mapCurrent`?

**Comment by stoeffel** [comment]
yes, I think `update` should be renamed to `mapCurrent`. IMHO that
communicates better.

**Comment by wernerdegroot** [comment]
I've added the requested `map` and renamed the other functions as we discussed. Could you review it please?

As I was creating this code, I came up with [issue 10](https://github.com/wernerdegroot/listzipper/issues/10). What do you think?

**Comment by stoeffel** [comment]
awesome! will review tomorrow, okay?

**Comment by stoeffel** [comment]
💭 maybe `mapBefore/After` should be like : 

`mapBefore : (a -> a) -> Zipper a -> Zipper a`
instead of taking a `(List a -> List a)`

**Comment by wernerdegroot** [comment]
Before we go through with this, are you aware that we might lose some flexibility?

We can't do a 

``` elm
removeBefore : Zipper a -> Zipper a
removeBefore = mapBefore (always [])
```

anymore, whereas a user can always choose to implement the function you would like as

``` elm
mapBefore' : (a -> a) -> Zipper a -> Zipper a 
mapBefore' = mapBefore << List.map
```

**Comment by stoeffel** [comment]
you are right. hmmm... will think about that, but I see that this wouldn't
be a good change.

**Comment by stoeffel** [comment]
yes, let's keep it as is. It's definitely better with `(List a -> List a)`. although there are other ways to implement `removeBefore` (f.e. with public `Zipper` :-), or fromList).

Thanks for your great work btw.

**Comment by stoeffel** [comment]
I think this can be closed. Current master includes these changes and it looks great!
